name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t google_authenticator_extractor
    - name: Test
      run: docker run --rm google_authenticator_extractor ./test/command_test.sh

  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./scripts/macosx/install.sh
    - name: Build
      run: ./scripts/build.sh
    - name: Test
      run: ./test/command_test.sh
    - name: Build for x86_64-pc-windows-gnu
      run: ./scripts/build.sh x86_64-pc-windows-gnu
    - name: Build for x86_64-unknown-linux-gnu
      run: CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc ./scripts/build.sh x86_64-unknown-linux-gnu

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./scripts/ubuntu/install.sh
    - name: Build
      run: ./scripts/build.sh
    - name: Test
      run: ./test/command_test.sh
    - name: Build for x86_64-pc-windows-gnu
      run: ./scripts/build.sh x86_64-pc-windows-gnu
    - name: Build for x86_64-unknown-linux-gnu
      run: ./scripts/build.sh x86_64-unknown-linux-gnu