name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t google_authenticator_extractor
    - name: Test
      run: docker --rm run google_authenticator_extractor ./test/command_test.sh

  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install protobuf
      run: brew install protobuf && protoc --version
    - name: Build
      run: ./scripts/build.sh
    - name: Test
      run: ./test/command_test.sh

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install protobuf
      run: sudo apt install -y protobuf-compiler && protoc --version
    - name: Build
      run: ./scripts/build.sh
    - name: Test
      run: ./test/command_test.sh

  cross-build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./scripts/ubuntu/install.sh
    - name: Build for x86_64-pc-windows-gnu
      run: ./scripts/build.sh x86_64-pc-windows-gnu
    - name: Build for x86_64-unknown-linux-gnu
      run: ./scripts/build.sh x86_64-unknown-linux-gnu