name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-10.15
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'zhangyuan/google-authenticator-extractor'
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
    - name: Install dependencies
      run: ./scripts/macosx/install.sh
    - name: Build
      run: ./scripts/macosx/build.sh
    - name: Test
      run: cargo test
    - name: Release
      run: ./scripts/macosx/release.sh

  build-ubuntu:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'zhangyuan/google-authenticator-extractor'
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./scripts/ubuntu/install.sh
    - name: Build
      run: ./scripts/ubuntu/build.sh
    - name: Test
      run: cargo test
