name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install protobuf
      run: apt install -y protobuf-compiler && protoc --version
    - name: Build
      run: cargo build --release