name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./scripts/macosx/install.sh
    - name: Build binaries
      run: ./scripts/macosx/build.sh
    - name: Test
      run: cargo test
    - name: Release
      run: ./scripts/macosx/release.sh
    - name: Upload Binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'releases/google_authenticator_extractor*'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
